name: Feast Integration

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/main/anovos/feature_store/**'
      - 'src/main/main.py'
      - 'src/main/anovos/workflow.py'
      - 'config/configs_feast.yaml'
      - '.github/workflows/feast.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        include:
          - python: '3.7'
            spark: '2.4.8'
            hadoop: '2.7'
            java: '8'
            experimental: false
          - python: '3.9'
            spark: '3.1.3'
            hadoop: '3.2'
            java: '11'
            experimental: false
          - python: '3.10'
            spark: '3.2.1'
            hadoop: '3.2'
            java: '11'
            experimental: false
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - uses: vemonet/setup-spark@v1
        with:
          spark-version: ${{ matrix.spark }}
          hadoop-version: ${{ matrix.hadoop }}

      - name: Check SPARK_HOME
        run: |
          echo $SPARK_HOME
          ls $SPARK_HOME

      - name: Checkout code
        uses: actions/checkout@master

      - name: Load PIP cache
        uses: actions/cache@v3.0.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python}}-${{ hashFiles('./requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python}}-
            ${{ runner.os }}-pip-

      - name: Ensure clean environment
        run: |
          make clean build

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov wheel
          pip install -r requirements.txt

      - name: Set up Feast
        run: |
          pip install feast
          feast init anovos_repo
          cd anovos_repo
          feast apply
          pwd

      - name: Run the demo
        run: |
          cp config/configs_feast.yaml dist/configs.yaml
          cd dist/
          pwd
          ./spark-submit.sh

      - name: Reapply Feast to import generated features
        run: |
          cd anovos_repo
          feast apply
          feast materialize `date "+%Y-%m-%dT"` `date "+%Y-%m-%dT%H:%M:%S"`
      - name: Retrieve generated historical features
        run: |
          cd dist
          python -m anovos.feature_store.feature_retrieval ../anovos_repo/
